config/routes.rb
Bustavote::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :votes, only: [:create, :destroy, :update]
  resources :relationships, only: [:create, :destroy]
  root  'static_pages#home'
  match '/following', to: 'static_pages#following',    via: 'get'
  match '/signup',    to: 'users#new',            via: 'get'
  match '/signin',    to: 'sessions#new',         via: 'get'
  match '/signout',   to: 'sessions#destroy',     via: 'delete'  
  match '/help',      to: 'static_pages#help',    via: 'get'
  match '/about',     to: 'static_pages#about',   via: 'get'
  match '/contact',   to: 'static_pages#contact', via: 'get'
  match '/ask',       to: 'questions#ask',        via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if signed_in?
      @question  = current_user.questions.build
      @feed_items = current_user.public_feed.paginate(page: params[:page])
      @vote = Vote.new
      @comment = Comment.new
    end
  end

  def following
    if signed_in?
      @question  = current_user.questions.build
      @feed_items = current_user.feed.paginate(page: params[:page])
      @vote = Vote.new
      @comment = Comment.new
      @feed_togle = "following"
      render "home"
    end
  end

  def help
  end

  def about
  end  

  def contact
  end 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Bustavote</h1>
<p>
  Bustavote is an app to make asking for advice better.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Bustavote about the sample app at the
  <a href="#">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  WIP help page for Bustavote.
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
    </aside>
    <div class="span8">
      <ul id="feed_togle" class="nav nav-pills">
      
        <% if @feed_togle != "following" %>
          <li class="active"><%= link_to "Public feed", root_path %></li>
        <% else %>
          <li><%= link_to "Public feed", root_path %></li>
        <% end %>
        
        <% if @feed_togle == "following" %>
          <li class="active"><%= link_to "Following", following_path %></li>
        <% else %>
          <li><%= link_to "Following", following_path %></li>
        <% end %>
      
      </ul>
      <h3 id = "question_header">Questions Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to BustaVote</h1>

    <h2>
      This is the home page BustaVote.
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  </div>

<% end %>